---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: 'test/integration/data_bags'

platforms:
  - name: windows_2012_r2_standard
    driver_config:
      box: kensykora/windows_2012_r2_standard
    # driver:
    #   gui: true

suites:
  - name: default
    run_list:
      - recipe[chocolatey::default]
      - recipe[chocolatey_test::default]

    attributes:
